import Header from '@/components/layout/header/Header'
import Providers from '@/providers/Providers'
import type { Metadata } from 'next'
import { useMessages, useTimeZone } from 'next-intl'
import './globals.scss'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
	params: { locale },
}: Readonly<{
	children: React.ReactNode
	params: { locale: string }
}>) {
	const messages = useMessages()
	const timeZone = useTimeZone()
	return (
		<html lang={locale}>
			<body>
				<Providers locale={locale} messages={messages} timeZone={timeZone}>
					<Header />
					<main>{children}</main>
				</Providers>
			</body>
		</html>
	)
}
